
language: rust
cache: cargo
sudo: false
branches: master
os:
  -linux
  -windows
  -osx
git:
  depth: 1
rust:
  - 1.43.0
name: "libazdice"
before_script:
- cargo update
script:
- cargo build --release
